<a href="https://colab.research.google.com/github/urfavnada/Task-Python/blob/main/Task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1 align='center'><font color='red'> Task_4


1. [NumPy](#NumPy)
1. [oop](#oop)
3. [ProblemSolving](#ProblemSolving)


<a id='NumPy'></a>
<h1><font color='red'> NumPy

## 1.What does NumPy stand for?


#### A) Number Python
#### B)Numerator Python
#### C) Numerical Python
#### D)There is no full form, it is a stand-alone word  


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 2.What does the size attribute in numpy use to find?


#### A) number of items
#### B)shape
#### C) date & time
#### D)unique items
    

In [ ]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}

### 3.What is the purpose of zero() function?

#### A) To create a matrix with the first row and first column as 0
#### B) To create a matrix with diagonal elements as 0
#### C) To create a matrix with all elements as 0
#### D) To return an integer number 0


In [ ]:
A = False #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = True #@param {type:"boolean"}
D = False #@param {type:"boolean"}

<h1><font color='red'> Answer these question

### 4- create 1D, 2D and 3D arrays in NumPy? then returns the type of the elements stored in the NumPy array.

In [1]:
# One-Dimensional array

import numpy as np
MyArray = np.array(([1,2,3]))
print(MyArray)





[1 2 3]


In [3]:
# Two-Dimensional array

import numpy as np
MyArray2 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])
print(MyArray2)





[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# Three-Dimensional array
import numpy as np
MyArray3 = ([[[1,2,3.4],
              [5,6,7,8],
              [9,10,11,12]],
             [[13,14,15,16],
              [17,18,19,20],
              [21,22,23,24]]])
print(MyArray3)






[[[1, 2, 3.4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]


### 5-Reverse this array [[[1,2,3,4],[4,5,6,7],[7,8,9,10]]] in two ways......

In [5]:
# Method one

import numpy as np
Array1 = np.array([[[1, 2, 3, 4],
                    [4, 5, 6, 7],
                    [7, 8, 9, 10]]])
Array2 = Array1[::-1, ::-1, ::-1]
print(Array2)







[[[10  9  8  7]
  [ 7  6  5  4]
  [ 4  3  2  1]]]


In [6]:
# Method two
#>**hint**: use flipud function
import numpy as np
Array1 = np.array([[[1, 2, 3, 4],
                    [4, 5, 6, 7],
                    [7, 8, 9, 10]]])
Array2 = np.flip(Array1)
print(Array2)






[[[10  9  8  7]
  [ 7  6  5  4]
  [ 4  3  2  1]]]


## 6-Make this array as an array one dimensional

In [7]:
import numpy as np
Array1 = np.array([[[1,2,3,4],
                    [4,5,6,7],
                    [7,8,9,10]]])
Array2 = np.reshape(Array1,(-1))
print(Array2)

[ 1  2  3  4  4  5  6  7  7  8  9 10]


## 7- Create a 3X2 integer array and Prints its attributes¶
* Note: The element must be a type of unsigned int16. And print the following Attributes:

- The shape of an array.
- Array dimensions.
- The Length of each element of the array in bytes

In [8]:
import numpy as np
Array = np.array([[1, 3],
                     [2, 4],
                     [5, 7]], dtype=np.uint16)
print("The array :",Array)
print("The shape of the array :",Array.shape)
print("The array dimensions :",Array.ndim)
print("The length of each element :",Array.itemsize)

The array : [[1 3]
 [2 4]
 [5 7]]
The shape of the array : (3, 2)
The array dimensions : 2
The length of each element : 2


### 8- Return array of odd rows and even columns from below numpy array

* # Ordering the values of each Key and the print the key witht highest value.


> **`sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24],
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])`**


# The output should be:
* `expexted output :
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]`

* `Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]`*

## 9-How is np.mean() different from np.average() in NumPy?

*   List item
*   List item



In [ ]:
# np.mean() computes the simple arithmetic mean of an array
# while np.average() extends this functionality by allowing you to provide weights for the elements when computing the average

## 10-Count the frequency of a given positive value appearing in this NumPy array
## [1, 2, 1, 3, 5, 0, 0, 0, 2, 3] ?

In [11]:
import numpy as np
Array = np.array([1, 2, 1, 3, 5, 0, 0, 0, 2, 3])
unique_elements, counts_elements = np.unique(Array, return_counts=True)
print(np.asarray((unique_elements, counts_elements)))

[[0 1 2 3 5]
 [3 2 2 2 1]]


## 11-Show how is arr[:,0] different from arr[:,[0]]

In [ ]:
# arr[:,0] => return 1D array containing the elements from the first column.
# arr[:,[0]] => a new axis, effectively converting the selected column into a 2D array with a single column.

In [20]:
import numpy as np

MyArray = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
# first
column_0 = MyArray[:,0]
print("arr[:, 0]:")
print(column_0)

# second
column_0_2d = MyArray[:,[0]]
print("arr[:, [0]]:")
print(column_0_2d)

arr[:, 0]:
[1 4 7]
arr[:, [0]]:
[[1]
 [4]
 [7]]


### 12-How do you multiply these 2 NumPy array matrices [[15,16,17],[18,19,20],[21,22,23]]  &  [[20,21,22],[23,24,25],[26,27,28]] ?

In [21]:
import numpy as np
Array1 = np.array([[15,16,17],[18,19,20],[21,22,23]])
Array2 = np.array([[20,21,22],[23,24,25],[26,27,28]])
Multipluction = np.dot(Array1,Array2)
print(Multipluction)

[[1110 1158 1206]
 [1317 1374 1431]
 [1524 1590 1656]]


### 13 -Combine these 2 NumPy arrays [1,2,3] & [4,5,6] using vstack()     and hstack()

In [23]:
import numpy as np
Array1 = np.array([1, 2, 3])
Array2 = np.array([4, 5, 6])
vertical = np.vstack((Array1, Array2))
horizontal = np.hstack((Array1, Array2))
print(vertical)
print(horizontal)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


# <a id='oop'></a>
<h1><font color='red'> oop

# 1 - a "class" is ... </font>

<br> </br>
#### A) an instance variable
#### B) a code template for creating object
#### C) a function in python
#### D) a synonym for methods

In [24]:
A = False #@param {type:"boolean"}
B = True #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


# 2- What is a "docstring" ?</font>
<br> </br>
#### A) it is a sting literal specified in source code that is used to explain or document a specific segment of code
#### B) it is a class method that allows working with string documents
#### C) it is an alternative name for instance vaeiables of type string apprearing in classes
#### D) it is a synonym for code comments

In [25]:
A = True #@param {type:"boolean"}
B = False #@param {type:"boolean"}
C = False #@param {type:"boolean"}
D = False #@param {type:"boolean"}


## 3- Create a Bus class that inherits from the Vehicle class. Give the capacity argument of Bus.seating_capacity() a default value of 50.
- Use the following code for your parent Vehicle class:.
>   class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage
    def seating_capacity(self, capacity):
        return f"The seating capacity of a {self.name} is {capacity} passengers


In [13]:
class Vehicle:
    def __init__(self, name, max_speed, mileage):
        self.name = name
        self.max_speed = max_speed
        self.mileage = mileage

class Bus(Vehicle):
    def __init__(self, name, max_speed, capacity):
        super().__init__(name, max_speed)
        # i don't know the reason of the error
        self.capacity = capacity

    def seating_capacity(self):
        return f"The seating capacity of a {self.name} is {self.capacity} passengers"

MyBus = Bus("BMW", "X4 M", 50)
print(MyBus.seating_capacity())

TypeError: ignored

# <a id='ProblemSolving'></a>
<h1><font color='red'>Problem Solving


<a href='https://codeforces.com/problemset/problem/339/A'> **problem 1**

In [14]:
# Problem_1 Link:
s = input()

# Split the input string by '+', convert to integers, and sort
numbers = sorted(map(int, s.split('+')))

# Create the new sum string
new_s = '+'.join(map(str, numbers))

# Print the new sum string
print(new_s)




3+2+1
1+2+3


<a href='https://codeforces.com/problemset/problem/118/A'> **problem 2**

In [15]:
# Problem_2 Link:

def process_string(s):
    vowels = "AEIOUYaeiouy"
    processed_string = ""

    for char in s:
        if char not in vowels:
            processed_string += "." + char.lower()

    return processed_string

# Read the input string
input_string = input()

# Process the input string and print the result
result = process_string(input_string)
print(result)


tour
.t.r
